### ISSUE TITLE
Risolvere gli ultimi bug (non gravi)

### ISSUE THREAD

**Issue by alex3025** [rgbcraft/Industrial-Engineering#6]
Lista bug da risolvere:
- [x] Se il debugger non è in modalità avanzata e si fa click-destro sulla Smart Safe, si deve aprire l'interfaccia della safe.
- [x] Si può cambiare il pin della smart safe ad uno con meno cifre di quelle richieste.
- [x] Il fluid counter se rivolto con l'input verso il basso, mostra le texture sbagliate.
- [x] Il fluid counter conta di più di quello che dovrebbe contare.
- [x] Sono presenti crafting errati.

**Comment by MrDionesalvi** [comment]
- [ ] Controllare Crash quando collegato con Trade-O-Mat
