### ISSUE TITLE
Conflitto di crafting

### ISSUE THREAD

**Issue by lay4play** [rgbcraft/Industrial-Engineering#9]
### Che versione della mod stai usando?
1.1.0
### In cosa consiste il bug?
Inserendo due electric circuit (indifferentemente dal tipo)  nell'assembling machine inizierà subito il crafting del relativo ASIC senza considerare cosa c'è nell'altro slot

### Come si può riprodurre il bug?
Inserendo due electric circuit (indifferentemente dal tipo)  nell'assembling machine inizierà subito il crafting del relativo ASIC senza considerare cosa c'è nell'altro slot

### Cosa dovrebbe succedere altrimenti?
Dovrebbe controllare cose c'è negli altri slot e solo se l'altro slot è vuoto far partire il crafting degli ASIC

**Comment by alex3025** [comment]
Crafting cambiato.
